xm_symfony:
    repositories:
        auth_list:
            repository_class:     App\Infrastructure\Repository\AuthRepository
            aggregate_type:       App\Model\Auth\Auth
            aggregate_translator: Xm\SymfonyBundle\EventSourcing\Aggregate\AggregateTranslator
            stream_name:          'auth'
        enquiry_list:
            repository_class:     App\Infrastructure\Repository\EnquiryRepository
            aggregate_type:       App\Model\Enquiry\Enquiry
            aggregate_translator: Xm\SymfonyBundle\EventSourcing\Aggregate\AggregateTranslator
            stream_name:          'enquiry'
        page_list:
            repository_class:     App\Infrastructure\Repository\PageRepository
            aggregate_type:       App\Model\Page\Page
            aggregate_translator: Xm\SymfonyBundle\EventSourcing\Aggregate\AggregateTranslator
            stream_name:          'page'
        user_list:
            repository_class:     App\Infrastructure\Repository\UserRepository
            aggregate_type:       App\Model\User\User
            aggregate_translator: Xm\SymfonyBundle\EventSourcing\Aggregate\AggregateTranslator
            stream_name:          'user'

services:
    App\Model\Auth\AuthList: '@auth_list'
    App\Model\Enquiry\EnquiryList: '@enquiry_list'
    App\Model\Page\PageList: '@page_list'
    App\Model\User\UserList: '@user_list'
