overblog_graphql:
    definitions:
        default_field_resolver: Xm\SymfonyBundle\Infrastructure\GraphQl\Resolver\FieldResolver
        schema:
            query: Query
            mutation: Mutation
        mappings:
            auto_discover: false
            types:
                -
                    type: yaml
                    dir: "%kernel.project_dir%/config/graphql/types"
                    suffix: ~

    security:
        enable_introspection: '%kernel.debug%'

services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: false

    Xm\SymfonyBundle\Infrastructure\GraphQl\Type\:
        resource: '../../vendor/xm/symfony-bundle/Infrastructure/GraphQl/Type/*Type.php'
        tags: [ 'overblog_graphql.type' ]

    Xm\SymfonyBundle\Infrastructure\GraphQl\Resolver\:
        resource: '../../vendor/xm/symfony-bundle/Infrastructure/GraphQl/Resolver/*Resolver.php'
        tags: [ 'overblog_graphql.resolver' ]
