framework:
    mailer:
        dsn: '%env(MAILER_DSN)%'
        envelope:
            sender: '%env(FROM_EMAIL)%'
        headers:
            From: '%env(FROM_EMAIL_NAME)% <%env(FROM_EMAIL)%>'

when@dev:
    framework:
        mailer:
            envelope:
                # see https://symfony.com/doc/5.4/mailer.html#always-send-to-the-same-address
                recipients: ['%env(DEV_EMAIL)%']

when@test:
    framework:
        mailer:
            dsn: 'null://null'
