framework:
    messenger:
        # The bus that is going to be injected when injecting MessageBusInterface:
        default_bus: messenger.bus.commands

        # Create buses
        buses:
            messenger.bus.commands:
                middleware:
                    - Xm\SymfonyBundle\Messenger\CommandEnricherMiddleware
                    - Xm\SymfonyBundle\Messenger\CommandRecorderMiddleware
                    - Xm\SymfonyBundle\Messenger\CausationRecorderMiddleware
                    - Xm\SymfonyBundle\Messenger\FailureCatcherMiddleware
            messenger.bus.events:
                default_middleware: 'allow_no_handlers'
                middleware:
                    - App\Messenger\RunProjectionMiddleware
                    - Xm\SymfonyBundle\Messenger\FailureCatcherMiddleware

        # reset services after consuming messages
        reset_on_message: true

        # Uncomment this (and the failed transport below) to send failed messages to this transport for later handling.
        # failure_transport: failed

        transports:
            # https://symfony.com/doc/current/messenger.html#transport-configuration
            # async: '%env(MESSENGER_TRANSPORT_DSN)%'
            # failed: 'doctrine://default?queue_name=failed'
            # sync: 'sync://'

        routing:
            # Route your messages to the transports
            # 'App\Message\YourMessage': async

# when@test:
#    framework:
#        messenger:
#            transports:
#                # replace with your transport name here (e.g., my_transport: 'in-memory://')
#                # For more Messenger testing tools, see https://github.com/zenstruck/messenger-test
#                async: 'in-memory://'
