prooph_event_store:
    stores:
        default:
            event_store: 'Prooph\EventStore\EventStore'

    projection_managers:
        app:
            event_store: '@Prooph\EventStore\EventStore'
            connection:  '@app.pdo_connection'
            projections:
                user_projection:
                    read_model: App\Projection\User\UserReadModel
                    projection: App\Projection\User\UserProjection
                user_token_projection:
                    read_model: App\Projection\User\UserTokenReadModel
                    projection: App\Projection\User\UserTokenProjection
