services:
    Prooph\EventStore\EventStore: '@app.event_store.default'

    app.event_store.default:
        class: Prooph\EventStore\Pdo\MySqlEventStore
        arguments:
            $messageFactory: '@prooph_event_store.message_factory'
            $connection: '@app.pdo_connection'
            $persistenceStrategy: '@Xm\SymfonyBundle\EventStore\PersistenceStrategy\StreamStrategy'

    app.pdo_connection:
        class: PDO
        factory: '@Xm\SymfonyBundle\Doctrine\PdoProvider'
