prooph_event_store:
    stores:
        default:
            event_store: 'Prooph\EventStore\EventStore'

    projection_managers:
        app:
            event_store: '@Prooph\EventStore\EventStore'
            connection: '@app.event_store.pdo_connection.mysql'
            projections:
                user_projection:
                    read_model: Xm\SymfonyBundle\Projection\User\UserReadModel
                    projection: Xm\SymfonyBundle\Projection\User\UserProjection
                user_token_projection:
                    read_model: Xm\SymfonyBundle\Projection\User\UserTokenReadModel
                    projection: Xm\SymfonyBundle\Projection\User\UserTokenProjection
                enquiry_projection:
                    read_model: App\Projection\Enquiry\EnquiryReadModel
                    projection: App\Projection\Enquiry\EnquiryProjection

services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: false

    # projections & read models
    #    Xm\SymfonyBundle\Projection\User\UserProjection: ~
    Xm\SymfonyBundle\Projection\User\UserReadModel: ~
    #    Xm\SymfonyBundle\Projection\User\UserTokenProjection: ~
    Xm\SymfonyBundle\Projection\User\UserTokenReadModel: ~
    #    App\Projection\Enquiry\EnquiryProjection: ~
    App\Projection\Enquiry\EnquiryReadModel: ~
