prooph_event_store:
    stores:
        default:
            event_store: 'Prooph\EventStore\EventStore'

    projection_managers:
        app:
            event_store: '@Prooph\EventStore\EventStore'
            connection: '@app.event_store.pdo_connection.mysql'
            projections:
                enquiry_projection:
                    read_model: App\Projection\Enquiry\EnquiryReadModel
                    projection: App\Projection\Enquiry\EnquiryProjection
                user_projection:
                    read_model: App\Projection\User\UserReadModel
                    projection: App\Projection\User\UserProjection
                user_token_projection:
                    read_model: App\Projection\User\UserTokenReadModel
                    projection: App\Projection\User\UserTokenProjection
