twig:
    default_path:     '%kernel.project_dir%/templates'
    debug:            '%kernel.debug%'
    strict_variables: '%kernel.debug%'
    globals:
        ga_tracking_id: '%env(GA_TRACKING_ID)%'
        form_themes:
            - 'Form/fields.html.twig'
#            - 'VichUploaderBundle:Form:fields.html.twig'

when@test:
    twig:
        strict_variables: true
