stages:
  - deploy

# Select image from https://hub.docker.com/_/php/
image: php:7.3-cli

# Select what we should cache
cache:
  paths:
    - vendor/
    - node_modules/

variables:
  APP_ENV: prod
  RELEASES: "$REMOTE_BASE/releases"
  SHARED: "$REMOTE_BASE/shared"

before_script:
  # setup SSH & private key
  - 'which ssh-agent || ( apt-get update -y && apt-get install openssh-client -yqq )'
  - eval $(ssh-agent -s)
  - echo "$SSH_PRIVATE_KEY" | tr -d '\r' | ssh-add - > /dev/null
  - mkdir -p ~/.ssh; chmod 700 ~/.ssh
  - ssh-keyscan -p $REMOTE_PORT $REMOTE_SERVER >> ~/.ssh/known_hosts
  # the following line is optional (likely remove previous line)
  #- echo "$SSH_SERVER_HOSTKEYS" > ~/.ssh/known_hosts
  - chmod 644 ~/.ssh/known_hosts
  # Taken from here: https://gist.github.com/kwk/55bb5b6a4b7457bef38d
  # This forces dpkg to not call sync() after package extraction and speeds up install
  - echo "force-unsafe-io" > /etc/dpkg/dpkg.cfg.d/02apt-speedup
  # We don't need and apt cache in a container or recommendations
  - echo "Acquire::http {No-Cache=True;};" > /etc/apt/apt.conf.d/no-cache
  - echo 'APT::Install-Recommends "false";' > /etc/apt/apt.conf
  # Install packages
  - apt-get install gnupg2 build-essential libssl-dev -yqq
  - curl -sL https://deb.nodesource.com/setup_10.x | bash -
  # Install libs the php image doesn't have installed
  - apt-get install git zip unzip gcc g++ make nodejs rsync -yqq
  - alias nodejs=node
  # add package key for yarn
  - curl -sL https://dl.yarnpkg.com/debian/pubkey.gpg | apt-key add -
  - echo "deb https://dl.yarnpkg.com/debian/ stable main" | tee /etc/apt/sources.list.d/yarn.list
  - apt-get update -yqq && apt-get install yarn -yqq
  - curl -sS https://getcomposer.org/installer | php

deploy:
  stage: deploy
  when: manual
  allow_failure: false
  only:
    - master
  script:
    - php -v
    - php composer.phar --version
    - node --version
    - yarn --version
    # setup vars for paths
    - TIMESTAMP=$(date +%s); RELEASE="$RELEASES/$TIMESTAMP"
    - echo "Paths:"; echo $REMOTE_BASE; echo $RELEASE; echo $SHARED
    - echo "Remote:"; echo $REMOTE_USER@$REMOTE_SERVER:$REMOTE_PORT
    # create partial .env file
    - printf "APP_ENV=$APP_ENV\nREQUEST_CONTEXT_HOST=$REQUEST_CONTEXT_HOST\nREQUEST_CONTEXT_SCHEME=$REQUEST_CONTEXT_SCHEME\n" > .env.local && cat .env.local
    # install php dependencies
    - php composer.phar install --no-dev --classmap-authoritative --no-interaction --no-progress --no-scripts --no-plugins --ignore-platform-reqs
    # check for security issues in PHP libs
    - php bin/console security:check
    - php composer.phar static
    # Install node/JS dependencies
    - yarn install --non-interactive --frozen-lockfile
    # check for JS security issues in libs
    - yarn audit:moderate
    - yarn lint:js
    - yarn build
    # add .revision file
    - git rev-parse --verify --short HEAD > .revision
    # ensure based paths exist
    - ssh -p $REMOTE_PORT $REMOTE_USER@$REMOTE_SERVER "mkdir -p $RELEASES $SHARED $SHARED/var $SHARED/public/uploads"
    # sync files to release directory
    - rsync --archive --stats --human-readable --no-perms --exclude ".git/" --exclude ".idea/" --exclude "node_modules/" --exclude "cypress/" -e "ssh -p $REMOTE_PORT" . $REMOTE_USER@$REMOTE_SERVER:$RELEASE
    # make bin files executable
    - ssh -p $REMOTE_PORT $REMOTE_USER@$REMOTE_SERVER "cd $RELEASE; chmod u+x bin/*"
    # ensure platform has all requirements
    - ssh -p $REMOTE_PORT $REMOTE_USER@$REMOTE_SERVER "cd $RELEASE; php composer.phar check-platform-reqs"
    # link shared folders
    - ssh -p $REMOTE_PORT $REMOTE_USER@$REMOTE_SERVER "rm -rf $RELEASE/var; ln -s $SHARED/var $RELEASE/var; rm -rf $RELEASE/public/uploads; ln -s $SHARED/public/uploads $RELEASE/public/uploads"
    # switch to new version
    - ssh -p $REMOTE_PORT $REMOTE_USER@$REMOTE_SERVER "ln -sfn $RELEASE $REMOTE_BASE/current"
    # copy env file into place; dump env
    - ssh -p $REMOTE_PORT $REMOTE_USER@$REMOTE_SERVER "cp -a $SHARED/.env.local $RELEASE/.env.local && cd $REMOTE_BASE/current && php composer.phar dump-env prod"
    # run composer post update cmds on server
    - ssh -p $REMOTE_PORT $REMOTE_USER@$REMOTE_SERVER "cd $REMOTE_BASE/current && rm -rf var/cache/prod/* && php composer.phar run-script post-update-cmd"
    # reload php-fpm (to reset cache)
    - ssh -p $REMOTE_PORT $REMOTE_USER@$REMOTE_SERVER "sudo /sbin/service php73-php-fpm reload"
    # run all projections (with 2GB memory)
    - ssh -p $REMOTE_PORT $REMOTE_USER@$REMOTE_SERVER "cd $REMOTE_BASE/current; php -d memory_limit=2048M bin/console app:projection:run --run-all"
    # cloudflare: purge cache
    #- ssh -p $REMOTE_PORT $REMOTE_USER@$REMOTE_SERVER "cd $RELEASE; php bin/console app:cloudflare:purge-cache"
    # remove >2 releases
    - ssh -p $REMOTE_PORT $REMOTE_USER@$REMOTE_SERVER "ls -1d $RELEASES/* | sort -rg | tail -n +3 | xargs /bin/rm -rf"
    # success message
    - echo "Deployment completed successfully. Release at $RELEASE"
