default:
  image: xmmedia/php:7.4-cli
  timeout: 15m

stages:
  - static
  - deploy

# Select what we should cache
cache:
  # cache per stage & branch
  key: "$CI_JOB_STAGE-$CI_COMMIT_REF_SLUG"
  paths:
    - vendor/
    - node_modules/

variables:
  SERVER_PHP_PATH: php74
  APP_ENV: prod
  RELEASES: "$REMOTE_BASE/releases"
  SHARED: "$REMOTE_BASE/shared"

before_script:
  # ensure everything up to date
  - apt-get update -yqq
  # install composer
  - wget --no-verbose -O composer.phar https://getcomposer.org/download/latest-2.x/composer.phar

.versions-script: &versions-script
  - php -v
  - php composer.phar --version
  - node --version
  - yarn --version

.security-checks: &security-checks
  # check for security issues in PHP libs
  - /root/.symfony/bin/symfony security:check
  # check for JS security issues in libs
  - yarn audit:high

static:
  stage: static
  allow_failure: false
  interruptible: true
  script:
    - *versions-script
    # install php dependencies
    - php composer.phar install --classmap-authoritative --no-interaction --no-progress --ignore-platform-reqs
    # Install node/JS dependencies
    - yarn install --non-interactive --frozen-lockfile
    - *security-checks
    # cache warmup for phpstan
    - php bin/console cache:warmup --env=dev
    - php bin/phpstan analyse --no-progress --memory-limit 1G src
    # lint JS
    - yarn lint:js
    - yarn lint:css
    # @todo artifacts

deploy:
  stage: deploy
  when: manual
  allow_failure: false
  only:
    - master
  script:
    - *versions-script
    # setup vars for paths
    - TIMESTAMP=$(date +%s); RELEASE="$RELEASES/$TIMESTAMP"
    - echo "Paths:"; echo $REMOTE_BASE; echo $RELEASE; echo $SHARED
    - echo "Remote:"; echo $REMOTE_USER@$REMOTE_SERVER:$REMOTE_PORT
    # setup SSH & private key
    - eval $(ssh-agent -s)
    - echo "$SSH_PRIVATE_KEY" | tr -d '\r' | ssh-add - > /dev/null
    - ssh-keyscan -p $REMOTE_PORT $REMOTE_SERVER >> ~/.ssh/known_hosts
    # the following line is optional (likely remove previous line)
    #- echo "$SSH_SERVER_HOSTKEYS" > ~/.ssh/known_hosts
    - chmod 644 ~/.ssh/known_hosts
    # add .revision file
    - git rev-parse --verify --short HEAD > .revision
    # create partial .env file
    - printf "APP_ENV=$APP_ENV\nREQUEST_CONTEXT_HOST=$REQUEST_CONTEXT_HOST\nREQUEST_CONTEXT_SCHEME=$REQUEST_CONTEXT_SCHEME\n" > .env.local && cat .env.local
    # install php dependencies without dev
    - php composer.phar install --no-dev --classmap-authoritative --no-interaction --no-progress --ignore-platform-reqs
    - yarn install --non-interactive --frozen-lockfile
    - *security-checks
    - yarn build
    # remove temp .env file just incase
    - rm .env.local
    # ensure based paths exist
    - ssh -p $REMOTE_PORT $REMOTE_USER@$REMOTE_SERVER "mkdir -p $RELEASES $SHARED $SHARED/var $SHARED/var/log/archive $SHARED/public/uploads"
    # sync files to release directory
    - rsync --archive --stats --human-readable --no-perms --exclude ".git/" --exclude ".idea/" --exclude "node_modules/" --exclude "cypress/" -e "ssh -p $REMOTE_PORT" . $REMOTE_USER@$REMOTE_SERVER:$RELEASE
    # make console file executable
    - ssh -p $REMOTE_PORT $REMOTE_USER@$REMOTE_SERVER "cd $RELEASE; chmod u+x bin/console"
    # ensure platform has all requirements
    - ssh -p $REMOTE_PORT $REMOTE_USER@$REMOTE_SERVER "cd $RELEASE; $SERVER_PHP_PATH -v; echo "\n\n"; $SERVER_PHP_PATH composer.phar check-platform-reqs"
    # link shared folders
    - ssh -p $REMOTE_PORT $REMOTE_USER@$REMOTE_SERVER "rm -rf $RELEASE/var || true; ln -s $SHARED/var $RELEASE/var; rm -rf $RELEASE/public/uploads || true; ln -s $SHARED/public/uploads $RELEASE/public/uploads"
    # switch to new version
    - ssh -p $REMOTE_PORT $REMOTE_USER@$REMOTE_SERVER "ln -sfn $RELEASE $REMOTE_BASE/current"
    # copy env file into place; dump env
    - ssh -p $REMOTE_PORT $REMOTE_USER@$REMOTE_SERVER "cp -a $SHARED/.env.local $RELEASE/.env.local && cd $REMOTE_BASE/current && $SERVER_PHP_PATH composer.phar dump-env prod"
    # run composer post update cmds on server
    - ssh -p $REMOTE_PORT $REMOTE_USER@$REMOTE_SERVER "cd $REMOTE_BASE/current && rm -rf var/cache/prod/* || true && $SERVER_PHP_PATH composer.phar run-script post-update-cmd"
    # reload php-fpm (to reset cache)
    - ssh -p $REMOTE_PORT $REMOTE_USER@$REMOTE_SERVER "sudo /bin/systemctl reload php74-php-fpm"
    # run all projections (with 2GB memory)
    - ssh -p $REMOTE_PORT $REMOTE_USER@$REMOTE_SERVER "cd $REMOTE_BASE/current; $SERVER_PHP_PATH -d memory_limit=2048M bin/console app:projection:run --run-all"
    # remove >2 releases
    - ssh -p $REMOTE_PORT $REMOTE_USER@$REMOTE_SERVER "ls -1d $RELEASES/* | sort -rg | tail -n +3 | xargs /bin/rm -rf"
    # test if website is up
    - if wget --spider --server-response "$REQUEST_CONTEXT_SCHEME://$REQUEST_CONTEXT_HOST" 2>&1 | grep '200\ OK'; then echo "$REQUEST_CONTEXT_SCHEME://$REQUEST_CONTEXT_HOST is up"; else echo "$REQUEST_CONTEXT_SCHEME://$REQUEST_CONTEXT_HOST is down"; exit 1; fi
    # success message
    - echo "Deployment completed successfully. Release at $RELEASE"
