# DB URL: mysql://symfony:symfony@database:3306/symfony?serverVersion=5.7
# @todo-symfony update
name: symfonystarter
recipe: symfony
config:
  php: '8.0'
  webroot: public
  xdebug: true
services:
  phpmyadmin:
    type: phpmyadmin
    hosts:
      - database
proxy:
  appserver:
    # @todo-symfony update
    - symfonystarter.lndo.site
