# @todo-symfony update
# URL: https://symfonystarter.lndo.site
# DB URL: mysql://symfony:symfony@database:3306/symfony?serverVersion=5.7&charset=utf8mb4
# @todo-symfony update
name: symfonystarter
recipe: symfony
config:
  php: '8.2'
  webroot: public
  xdebug: true
services:
  appserver:
    build_as_root:
      - a2enmod headers
  phpmyadmin:
    type: phpmyadmin
    ssl: true
    sslExpose: false
    hosts:
      - database
proxy:
  appserver:
    # @todo-symfony update
    - symfonystarter.lndo.site
  phpmyadmin:
    # @todo-symfony update
    - pma.symfonystarter.lndo.site
