overblog_graphql_endpoint:
    path: /graphql
    defaults:
        _controller: Overblog\GraphQLBundle\Controller\GraphController::endpointAction
        _format: "json"
    methods: [POST]

overblog_graphql_batch_endpoint:
    path: /graphql/batch
    defaults:
        _controller: Overblog\GraphQLBundle\Controller\GraphController::batchEndpointAction
        _format: "json"
    methods: [POST]
