web_profiler:
    toolbar: true
    intercept_redirects: false
    excluded_ajax_paths: '^/(sockjs\-node|dev\-server|((index|app(_[\w]+)?)\.php/)?_wdt)'

framework:
    profiler: { only_exceptions: false }
