cms:
    templates:
        static.html.twig:
            name: 'Default'
            items:
                pageTitle:
                    type: text
                    name: 'Page Title'
                    required: true
# @todo help
                    params:
                        - [min, 3]
                        - [max, 25]
                content:
                    type: html
                    name: 'Content'

        default/index.html.twig:
            name: 'Home Page'
            # edit_meta_description: false
