CountryQuery:
    decorator: true
    heirs: [Query]
    config:
        fields:
            Countries:
                type: '[Country!]!'
                description: 'Retrieve all Countries.'
                public: '@=isAuthenticated()'
                access: '@=isAuthenticated()'
                resolve: '@=resolver("Xm\\SymfonyBundle\\Infrastructure\\GraphQl\\Resolver\\CountryResolver")'
