CountryQuery:
    decorator: true
    heirs: [ Query ]
    config:
        fields:
            Countries:
                type:        '[Country!]!'
                description: 'Retrieve all Countries.'
                access:      '@=isAuthenticated()'
                resolve:     '@=query("Xm\\SymfonyBundle\\Infrastructure\\GraphQl\\Query\\CountryQuery")'
