EnquiryMutation:
    decorator: true
    heirs: [ Mutation ]
    config:
        fields:
            SendEnquiry:
                type:    EnquiryPayload!
                resolve: '@=mutation("App\\Infrastructure\\GraphQl\\Mutation\\SendEnquiryMutation", args)'
                args:
                    enquiry: EnquiryInput!

EnquiryInput:
    type: input-object
    config:
        description: 'Send Enquiry input.'
        fields:
            name:    String!
            email:   String!
            message: String!

EnquiryPayload:
    type: object
    config:
        description: 'Send Enquiry mutation payload.'
        fields:
            success: Boolean!
