Mutation:
    type: object
    config:
        description: 'Main Mutations'
        # uncomment if all the mutations are removed
#        fields:
#            # so there's always a mutation available
#            Ping:
#                type: Boolean!
#                description: 'A default query so public pages have a mutation.'
#                resolve: '@=true'
