ProvinceQuery:
    decorator: true
    heirs: [Query]
    config:
        fields:
            Provinces:
                type: '[Province!]!'
                description: 'Retrieve all Provinces.'
                public: '@=isAuthenticated()'
                access: '@=isAuthenticated()'
                resolve: '@=resolver("Xm\\SymfonyBundle\\Infrastructure\\GraphQl\\Resolver\\ProvinceResolver")'
