ProvinceQuery:
    decorator: true
    heirs: [ Query ]
    config:
        fields:
            Provinces:
                type:        '[Province!]!'
                description: 'Retrieve all Provinces.'
                access:      '@=isAuthenticated()'
                resolve:     '@=query("Xm\\SymfonyBundle\\Infrastructure\\GraphQl\\Query\\ProvinceQuery")'
