Query:
    type: object
    config:
        description: 'Main Queries'
        fields:
            Me:
                type:        User
                description: 'The current User object or null.'
                access:      '@=isAuthenticated()'
                resolve:     '@=getUser()'

            EntrypointIntegrity:
                type:        String
                description: 'Retrieve the current integrity hash for a script (JavaScript) file.'
                resolve:     '@=resolver("Xm\\SymfonyBundle\\Infrastructure\\GraphQl\\Resolver\\EntrypointIntegrityHashResolver", [args["entrypoint"]])'
                args:
                    entrypoint:
                        type: String!
