Query:
    type: object
    config:
        description: 'Main Queries'
        fields:
            Me:
                type:        User
                description: 'The current User object or null.'
                access:      '@=isAuthenticated()'
                resolve:     '@=getUser()'

            EntrypointIntegrity:
                type:        String
                description: 'Retrieve the current integrity hash for a script (JavaScript) file.'
                resolve:     '@=query("Xm\\SymfonyBundle\\Infrastructure\\GraphQl\\Query\\EntrypointIntegrityHashQuery", args["entrypoint"])'
                args:
                    entrypoint: String!
