CmsQuery:
    decorator: true
    heirs: [Query]
    config:
        fields:
            Templates:
                type: '[Template!]!'
                description: 'Retrieve all configured Templates.'
                public: '@=hasRole("ROLE_ADMIN")'
                access: '@=hasRole("ROLE_ADMIN")'
                resolve: '@=resolver("App\\Infrastructure\\GraphQl\\Resolver\\Template\\TemplatesResolver")'

            Template:
                type: Template
                description: 'Retrieve a single Template.'
                public: '@=hasRole("ROLE_ADMIN")'
                access: '@=hasRole("ROLE_ADMIN")'
                resolve: '@=resolver("App\\Infrastructure\\GraphQl\\Resolver\\Template\\TemplateResolver", [args["template"]])'
                args:
                    template: String!
