UserMutation:
    decorator: true
    heirs: [ Mutation ]
    config:
        fields:
            UserUpdateProfile:
                type:        UserMutationPayload!
                description: 'Update User profile.'
                access:      '@=isAuthenticated()'
                resolve:     '@=mutation("App\\Infrastructure\\GraphQl\\Mutation\\User\\UserUpdateProfileMutation", [args])'
                args:
                    user: UserUpdateProfileInput!

            ChangePassword:
                type:        UserMutationPayload!
                description: 'Change User password.'
                access:      '@=isAuthenticated()'
                resolve:     '@=mutation("App\\Infrastructure\\GraphQl\\Mutation\\User\\UserPasswordMutation", [args])'
                args:
                    user: UserPasswordInput!

            UserRecoverInitiate:
                type:        UserResultPayload!
                description: 'Initiate User account recovery.'
                resolve:     '@=mutation("App\\Infrastructure\\GraphQl\\Mutation\\User\\UserRecoverInitiateMutation", [args])'
                args:
                    email: String!

            UserRecoverReset:
                type:        UserResultPayload!
                description: 'Set User password with User token.'
                resolve:     '@=mutation("App\\Infrastructure\\GraphQl\\Mutation\\User\\UserRecoverResetMutation", [args])'
                args:
                    token:       String!
                    newPassword: String!

            UserVerify:
                type:        UserResultPayload!
                description: 'Verify (activate) User account with password and User token.'
                resolve:     '@=mutation("App\\Infrastructure\\GraphQl\\Mutation\\User\\UserVerifyMutation", [args])'
                args:
                    token:    String!
                    password: String!

            AdminUserAdd:
                type:        AdminUserAddMutationPayload!
                description: 'Admin User add.'
                access:      '@=hasRole("ROLE_ADMIN")'
                resolve:     '@=mutation("App\\Infrastructure\\GraphQl\\Mutation\\User\\AdminUserAddMutation", [args])'
                args:
                    user: AdminUserAddInput!

            AdminUserUpdate:
                type:        AdminUserMutationPayload!
                description: 'Admin User update.'
                access:      '@=hasRole("ROLE_ADMIN")'
                resolve:     '@=mutation("App\\Infrastructure\\GraphQl\\Mutation\\User\\AdminUserUpdateMutation", [args])'
                args:
                    user: AdminUserUpdateInput!

            AdminUserActivate:
                type:        AdminUserMutationPayload!
                description: 'Activate User by Admin.'
                access:      '@=hasRole("ROLE_ADMIN")'
                resolve:     '@=mutation("App\\Infrastructure\\GraphQl\\Mutation\\User\\AdminUserActivateMutation", [args])'
                args:
                    user: AdminUserActivateInput!

            AdminUserVerify:
                type:        AdminUserMutationPayload!
                description: 'Verify User by Admin.'
                access:      '@=hasRole("ROLE_ADMIN")'
                resolve:     '@=mutation("App\\Infrastructure\\GraphQl\\Mutation\\User\\AdminUserVerifyMutation", [args["userId"]])'
                args:
                    userId: UUID!

            AdminUserSendReset:
                type:        AdminUserMutationPayload!
                description: 'Send User a password reset link.'
                access:      '@=hasRole("ROLE_ADMIN")'
                resolve:     '@=mutation("App\\Infrastructure\\GraphQl\\Mutation\\User\\AdminUserSendResetToUserMutation", [args["userId"]])'
                args:
                    userId: UUID!

            AdminUserSendActivation:
                type:        AdminUserMutationPayload!
                description: 'Send User a their activation link.'
                access:      '@=hasRole("ROLE_ADMIN")'
                resolve:     '@=mutation("App\\Infrastructure\\GraphQl\\Mutation\\User\\AdminUserSendActivationToUserMutation", [args["userId"]])'
                args:
                    userId: UUID!

UserUpdateProfileInput:
    type: input-object
    config:
        description: 'User profile update mutation input.'
        fields:
            email:
                type: String!
            firstName:
                type: String!
            lastName:
                type: String!

UserPasswordInput:
    type: input-object
    config:
        description: 'User update mutation input.'
        fields:
            currentPassword:
                type: String!
            newPassword:
                type: String!

AdminUserInput:
    type: input-object
    config:
        description: 'Admin User add mutation input.'
        fields:
            userId:
                type: UUID!
            email:
                type: String!
            password:
                type: String
            firstName:
                type: String!
            lastName:
                type: String!

AdminUserAddInput:
    type: input-object
    inherits: [ AdminUserInput ]
    config:
        description: 'Admin User add mutation input.'
        fields:
            setPassword:
                type: Boolean!
            role:
                type: Role!
            active:
                type: Boolean!
            sendInvite:
                type: Boolean!

AdminUserUpdateInput:
    type: input-object
    inherits: [ AdminUserInput ]
    config:
        description: 'Admin User update mutation input.'
        fields:
            setPassword:
                type: Boolean!
            role:
                type: Role!

AdminUserActivateInput:
    type: input-object
    config:
        description: 'Admin User activate/deactivate mutation input.'
        fields:
            userId:
                type: UUID!
            action:
                type: String!

UserMutationPayload:
    type: object
    config:
        description: 'User mutation payload.'
        fields:
            success:
                type: Boolean!

UserResultPayload:
    type: object
    config:
        description: 'Payload if the User mutation was successful.'
        fields:
            success:
                type: Boolean!

AdminUserMutationPayload:
    type: object
    config:
        description: 'Admin User mutation payload.'
        fields:
            userId:
                type: UUID!

AdminUserAddMutationPayload:
    type: object
    inherits: [ AdminUserMutationPayload ]
    config:
        description: 'Admin User add mutation payload.'
        fields:
            email:
                type: String!
            active:
                type: Boolean!
