UserQuery:
    decorator: true
    heirs: [Query]
    config:
        fields:
            Users:
                type: '[User!]'
                description: 'Retrieve all Users or a subset based on the passed filters.'
                public: '@=hasRole("ROLE_ADMIN")'
                access: '@=hasRole("ROLE_ADMIN")'
                resolve: '@=resolver("App\\Infrastructure\\GraphQl\\Resolver\\User\\UsersResolver", [args["filters"]])'
                args:
                    filters: UserFilterInput

            User:
                type: User
                description: 'Retrieve a single User.'
                public: '@=hasRole("ROLE_ADMIN")'
                access: '@=hasRole("ROLE_ADMIN")'
                resolve: '@=resolver("App\\Infrastructure\\GraphQl\\Resolver\\User\\UserResolver", [args["userId"]])'
                args:
                    userId:
                        type: UUID!

            UserEmailUnique:
                type: UserEmailUnique!
                description: 'Check if an email address is unique. Excludes the current user.'
                public: '@=isAuthenticated()'
                access: '@=isAuthenticated()'
                resolve: '@=resolver("App\\Infrastructure\\GraphQl\\Resolver\\User\\UserEmailUniqueResolver", [args["email"]])'
                args:
                    email: String!

            UserPasswordValid:
                type: UserPasswordValid!
                description: 'Check if the password is valid/correct for the current user.'
                public: '@=isAuthenticated()'
                access: '@=isAuthenticated()'
                resolve: '@=resolver("App\\Infrastructure\\GraphQl\\Resolver\\User\\UserPasswordValidResolver", [args["password"]])'
                args:
                    password: String!

UserFilterInput:
    type: input-object
    config:
        description: 'Available filters for querying users. Any passed fields will be applied. Exclude the key/field to skip that filter.'
        fields:
            email:
                type: String
            emailExact:
                type: String
            active:
                type: Boolean

UserEmailUnique:
    type: object
    config:
        fields:
            unique:
                type: Boolean!

UserPasswordValid:
    type: object
    config:
        fields:
            valid:
                type: Boolean!
