UserMutation:
    decorator: true
    heirs: [Mutation]
    config:
        fields:
            # @todo rename to Admin... (because of profile edit)
            CreateUser:
                type: UserMutationPayload!
                public: '@=hasRole("ROLE_ADMIN")'
                access: '@=hasRole("ROLE_ADMIN")'
                resolve: '@=mutation("App\\Infrastructure\\GraphQl\\Mutation\\UserCreateMutation", [args])'
                args:
                    user: UserCreateInput!
            UpdateUser:
                type: UserMutationPayload!
                public: '@=hasRole("ROLE_ADMIN")'
                access: '@=hasRole("ROLE_ADMIN")'
                resolve: '@=mutation("App\\Infrastructure\\GraphQl\\Mutation\\UserUpdateMutation", [args])'
                args:
                    user: UserUpdateInput!
            ActivateUser:
                type: UserMutationPayload!
                public: '@=hasRole("ROLE_ADMIN")'
                access: '@=hasRole("ROLE_ADMIN")'
                resolve: '@=mutation("App\\Infrastructure\\GraphQl\\Mutation\\UserActivateMutation", [args])'
                args:
                    user: UserActivateInput!
            VerifyUser:
                type: UserMutationPayload!
                public: '@=hasRole("ROLE_ADMIN")'
                access: '@=hasRole("ROLE_ADMIN")'
                resolve: '@=mutation("App\\Infrastructure\\GraphQl\\Mutation\\UserVerifyMutation", [args])'
                args:
                    user: UserInput!
            SendResetToUser:
                type: UserMutationPayload!
                public: '@=hasRole("ROLE_ADMIN")'
                access: '@=hasRole("ROLE_ADMIN")'
                resolve: '@=mutation("App\\Infrastructure\\GraphQl\\Mutation\\UserSendResetToUserMutation", [args])'
                args:
                    user: UserInput!

UserCreateInput:
    type: input-object
    config:
        description: 'User create mutation input.'
        fields:
            id:
                type: UUID!
            email:
                type: String!
            setPassword:
                type: Boolean!
            password:
                type: String
            role:
                type: Role!
            active:
                type: Boolean!
            firstName:
                type: String!
            lastName:
                type: String!
            sendInvite:
                type: Boolean!

UserUpdateInput:
    type: input-object
    config:
        description: 'User update mutation input.'
        fields:
            id:
                type: UUID!
            email:
                type: String!
            changePassword:
                type: Boolean!
            password:
                type: String
            role:
                type: Role!
            firstName:
                type: String!
            lastName:
                type: String!

UserActivateInput:
    type: input-object
    config:
        description: 'User activate/deactivate mutation input.'
        fields:
            id:
                type: UUID!
            action:
                type: String!

UserInput:
    type: input-object
    config:
        description: 'User mutation input.'
        fields:
            id:
                type: UUID!

UserMutationPayload:
    type: object
    config:
        description: 'User mutation payload.'
        fields:
            id:
                type: UUID!
