UserQuery:
    decorator: true
    heirs: [Query]
    config:
        fields:
            Users:
                type: '[User!]'
                description: 'Retrieve all Users.'
                public: '@=hasRole("ROLE_ADMIN")'
                access: '@=hasRole("ROLE_ADMIN")'
                resolve: '@=resolver("App\\Infrastructure\\GraphQl\\Resolver\\User\\UsersResolver")'

            User:
                type: User
                description: 'Retrieve a single User.'
                public: '@=hasRole("ROLE_ADMIN")'
                access: '@=hasRole("ROLE_ADMIN")'
                resolve: '@=resolver("App\\Infrastructure\\GraphQl\\Resolver\\User\\UserResolver", [args["userId"]])'
                args:
                    userId:
                        type: UUID!
