admin_default:
    path: /admin/{dir1?}/{dir2?}/{dir3?}/{dir4?}
    controller: Symfony\Bundle\FrameworkBundle\Controller\TemplateController
    defaults:
        template: admin.html.twig
    methods: [GET]
