user_profile_edit:
    path:       /profile/edit
    controller: Symfony\Bundle\FrameworkBundle\Controller\TemplateController
    defaults:
        template: static/user_profile_edit.html.twig

admin_dashboard:
    path:       /admin
    controller: Symfony\Bundle\FrameworkBundle\Controller\TemplateController
    defaults:
        template: static/admin_dashboard.html.twig
