admin_default:
    path: /admin/{path}
    controller: Symfony\Bundle\FrameworkBundle\Controller\TemplateController
    defaults:
        template: admin.html.twig
    methods: [GET]
    requirements:
        path: '.*'

user_profile:
    path: /profile/{path}
    controller: Symfony\Bundle\FrameworkBundle\Controller\TemplateController
    defaults:
        template: admin.html.twig
    methods: [GET]
    requirements:
        path: '.*'

user_verify:
    path: /activate/{token}
    controller: Symfony\Bundle\FrameworkBundle\Controller\TemplateController
    defaults:
        template: admin.html.twig
    methods: [GET]
