user_profile:
    path:       /user/profile
    controller: Symfony\Bundle\FrameworkBundle\Controller\TemplateController
    defaults:
        template: static/user_profile.html.twig

admin_dashboard:
    path:       /admin
    controller: Symfony\Bundle\FrameworkBundle\Controller\TemplateController
    defaults:
        template: static/admin_dashboard.html.twig
