Address:
    type: object
    config:
        description: 'The Address object.'
        fields:
            line1:      String!
            line2:      String
            city:       String!
            province:   Province!
            postalCode: String!
            country:    Country!

AddressInput:
    type: input-object
    config:
        description: 'The Address input object.'
        fields:
            line1:      String!
            line2:      String
            city:       String!
            province:   ProvinceInput!
            postalCode: String!
            country:    CountryInput!

Province:
    type: object
    config:
        fields:
            country:      Country!
            name:         String!
            abbreviation: String!

Country:
    type: object
    config:
        fields:
            name:         String!
            abbreviation: String!
