Address:
    type: object
    config:
        description: 'The Address object.'
        fields:
            line1:
                type: String!
            line2:
                type: String
            city:
                type: String!
            province:
                type: Province!
            postalCode:
                type: String!
            country:
                type: Country!

AddressInput:
    type: input-object
    config:
        description: 'The Address input object.'
        fields:
            line1:
                type: String!
            line2:
                type: String
            city:
                type: String!
            province:
                type: ProvinceInput!
            postalCode:
                type: String!
            country:
                type: CountryInput!

Province:
    type: object
    config:
        fields:
            country:
                type: Country!
            name:
                type: String!
            abbreviation:
                type: String!

Country:
    type: object
    config:
        fields:
            name:
                type: String!
            abbreviation:
                type: String!
