Page:
    type: object
    config:
        description: 'The Page object.'
        fieldsDefaultPublic: '@=hasRole("ROLE_USER")'
        fields:
            pageId:
                type: UUID!
            path:
                type: String!
            template:
                type: Template!
                resolve: '@=resolver("App\\Infrastructure\\GraphQl\\Resolver\\Template\\TemplateResolver", [value.template()])'
            published:
                type: Boolean!
            title:
                type: String!
            content:
                type: String!
                description: 'JSON string'
                resolve: '@=resolver("App\\Infrastructure\\GraphQl\\Resolver\\JsonResolver", [value.content()])'
            lastModified:
                type: DateTime!
            lastModifiedBy:
                type: User
