Template:
    type: object
    config:
        description: 'The Template object.'
        fieldsDefaultPublic: '@=hasRole("ROLE_ADMIN")'
        fields:
            key:
                type: String!
            name:
                type: String!
            default:
                type: Boolean!
            items:
                type: '[ContentItem!]'

ContentItem:
    type: object
    config:
        description: 'The configuration for a content item.'
        fieldsDefaultPublic: '@=hasRole("ROLE_ADMIN")'
        fields:
            name:
                type: String!
            type:
                type: String!
            config:
                type: String!
                description: 'JSON string'
